export type ScenarioOrchestratorIssueCode =
  | "ORCHESTRATOR_SCHEMA_INVALID"
  | "ORCHESTRATOR_KIND_INVALID"
  | "ORCHESTRATOR_COMPOSITION_REF_INVALID"
  | "ORCHESTRATOR_EXECUTION_MODEL_UNSUPPORTED"
  | "ORCHESTRATOR_PREVIEW_FLAG_INVALID"
  | "ORCHESTRATOR_RUNTIME_EXECUTABLE_FORBIDDEN"
  | "ORCHESTRATOR_ENTRY_SLOT_INVALID"
  | "ORCHESTRATOR_PRIMARY_SLOT_MISSING"
  | "ORCHESTRATOR_MULTIPLE_PRIMARY_SLOTS"
  | "ORCHESTRATOR_SLOT_DUPLICATE"
  | "ORCHESTRATOR_SLOT_REF_INVALID"
  | "ORCHESTRATOR_SLOT_NAMESPACE_COLLISION"
  | "ORCHESTRATOR_SLOT_ARTIFACT_PATH_INVALID"
  | "ORCHESTRATOR_SLOT_ARTIFACT_HASH_MISSING"
  | "ORCHESTRATOR_ROUTE_DUPLICATE"
  | "ORCHESTRATOR_ROUTE_SOURCE_INVALID"
  | "ORCHESTRATOR_ROUTE_TARGET_INVALID"
  | "ORCHESTRATOR_ROUTE_PRIORITY_CONFLICT"
  | "ORCHESTRATOR_ROUTE_AMBIGUOUS"
  | "ORCHESTRATOR_SUPPORTING_CALL_NOT_ALLOWED"
  | "ORCHESTRATOR_SELF_CALL_NOT_ALLOWED"
  | "ORCHESTRATOR_CALL_DEPTH_UNSUPPORTED"
  | "ORCHESTRATOR_ROUTE_CYCLE_NOT_ALLOWED"
  | "ORCHESTRATOR_RESUME_WITHOUT_CALLER"
  | "ORCHESTRATOR_BINDING_INVALID"
  | "ORCHESTRATOR_CONTEXT_POLICY_INVALID"
  | "ORCHESTRATOR_IMPLICIT_MERGE_FORBIDDEN"
  | "ORCHESTRATOR_ADAPTER_INHERITANCE_FORBIDDEN"
  | "ORCHESTRATOR_SECRET_PROPAGATION_FORBIDDEN"
  | "ORCHESTRATOR_TERMINAL_INVALID"
  | "ORCHESTRATOR_PRIMARY_OUTPUT_REQUIRED"
  | "ORCHESTRATOR_PRECEDENCE_INCOMPLETE"
  | "ORCHESTRATOR_TRACE_POLICY_INCOMPLETE"
  | "ORCHESTRATOR_BUDGET_INVALID"
  | "ORCHESTRATOR_PROVENANCE_INVALID"
  | "ORCHESTRATOR_PUBLIC_BOUNDARY_INVALID"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_MISSING"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_INVALID"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_INCOMPLETE"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_EXTRA"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_PRIORITY_CONFLICT"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_PATH_UNSAFE"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_AMBIGUOUS"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_NO_MATCH"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_MARKER_UNKNOWN";

export type ScenarioOrchestratorIssue = {
  code: ScenarioOrchestratorIssueCode;
  message: string;
  path?: string[];
};

export type ScenarioOrchestratorValidationResult = {
  ok: boolean;
  issues: ScenarioOrchestratorIssue[];
};
