export type RuntimeAdapterContractErrorCode =
  | "RUNTIME_ADAPTER_DESCRIPTOR_INVALID"
  | "RUNTIME_ADAPTER_IMPLEMENTATION_UNAVAILABLE"
  | "RUNTIME_ADAPTER_PROTOCOL_UNSUPPORTED"
  | "RUNTIME_ADAPTER_ORCHESTRATOR_SCHEMA_UNSUPPORTED"
  | "RUNTIME_ADAPTER_EXECUTION_MODEL_UNSUPPORTED"
  | "RUNTIME_ADAPTER_AGENT_DSL_VERSION_UNSUPPORTED"
  | "RUNTIME_ADAPTER_CAPABILITY_MISSING"
  | "RUNTIME_ADAPTER_ARTIFACT_HASH_INVALID"
  | "RUNTIME_ADAPTER_ARTIFACT_HASH_MISMATCH"
  | "RUNTIME_ADAPTER_ACTION_CLOSURE_INCOMPLETE"
  | "RUNTIME_ADAPTER_IDEMPOTENCY_REQUIRED"
  | "RUNTIME_ADAPTER_INPUT_NAMESPACE_INVALID"
  | "RUNTIME_ADAPTER_INPUT_TOO_LARGE"
  | "RUNTIME_ADAPTER_TIMEOUT_INVALID"
  | "RUNTIME_ADAPTER_SIDE_EFFECT_LEVEL_EXCEEDED"
  | "RUNTIME_ADAPTER_TRACE_BINDING_REQUIRED"
  | "RUNTIME_ADAPTER_AUDIT_REQUIRED"
  | "RUNTIME_ADAPTER_RESULT_INVALID"
  | "RUNTIME_ADAPTER_OUTPUT_NAMESPACE_INVALID"
  | "RUNTIME_ADAPTER_PUBLIC_BOUNDARY_INVALID";

export type RuntimeAdapterContractIssue = {
  code: RuntimeAdapterContractErrorCode;
  message: string;
  path?: string[];
  capabilityId?: string;
  slotId?: string;
};

export type RuntimeAdapterValidationResult<T> =
  | {
      ok: true;
      value: T;
      issues: [];
    }
  | {
      ok: false;
      value?: never;
      issues: RuntimeAdapterContractIssue[];
    };
