export const RUNTIME_ERROR_CODES = {
  INVALID_INITIAL_STATE: "RUNTIME_INVALID_INITIAL_STATE",
  GUARD_EVALUATION_FAILED: "RUNTIME_GUARD_EVALUATION_FAILED",
  ACTION_NOT_FOUND: "RUNTIME_ACTION_NOT_FOUND",
  ACTION_TIMEOUT: "RUNTIME_ACTION_TIMEOUT",
  ACTION_FAILED: "RUNTIME_ACTION_FAILED",
  TRANSITION_RESOLUTION_FAILED: "RUNTIME_TRANSITION_RESOLUTION_FAILED",
  NO_NEXT_STEP: "RUNTIME_NO_NEXT_STEP",
  MAX_STEPS_EXCEEDED: "RUNTIME_MAX_STEPS_EXCEEDED",
  MAX_DURATION_EXCEEDED: "RUNTIME_MAX_DURATION_EXCEEDED",
  MAX_EXTERNAL_CALLS_EXCEEDED: "RUNTIME_MAX_EXTERNAL_CALLS_EXCEEDED",
  CONTEXT_MERGE_FAILED: "RUNTIME_CONTEXT_MERGE_FAILED",
  CONTEXT_MERGE_CONFLICT: "RUNTIME_CONTEXT_MERGE_CONFLICT",
  CONTEXT_PATCH_INVALID: "RUNTIME_CONTEXT_PATCH_INVALID",
  IDEMPOTENCY_CONFLICT: "RUNTIME_IDEMPOTENCY_CONFLICT",
  SKILL_INPUT_INVALID: "SKILL_INPUT_INVALID",
  SKILL_OUTPUT_INVALID: "SKILL_OUTPUT_INVALID",
  SKILL_ENTRY_MISSING: "SKILL_ENTRY_MISSING",
  SKILL_ENTRY_INVALID: "SKILL_ENTRY_INVALID",
  SKILL_EXECUTION_FAILED: "SKILL_EXECUTION_FAILED",
  SKILL_MANIFEST_INVALID: "SKILL_MANIFEST_INVALID",
  POLICY_ACTION_DENIED: "POLICY_ACTION_DENIED",
  POLICY_SIDEEFFECT_DENIED: "POLICY_SIDEEFFECT_DENIED",
  POLICY_HANDOFF_REQUIRED: "POLICY_HANDOFF_REQUIRED"
} as const;

export const ACTION_ERROR_CODES = {
  TIMEOUT: "ACTION_TIMEOUT"
} as const;

export type RuntimeErrorCode = (typeof RUNTIME_ERROR_CODES)[keyof typeof RUNTIME_ERROR_CODES];
export type ActionErrorCode = (typeof ACTION_ERROR_CODES)[keyof typeof ACTION_ERROR_CODES];
