export const SKILL_ERROR_CODES = {
  SKILL_MANIFEST_MISSING: "SKILL_MANIFEST_MISSING",
  SKILL_MANIFEST_INVALID: "SKILL_MANIFEST_INVALID",
  SKILL_NAME_INVALID: "SKILL_NAME_INVALID",
  SKILL_VERSION_INVALID: "SKILL_VERSION_INVALID",
  SKILL_ENTRY_MISSING: "SKILL_ENTRY_MISSING",
  SKILL_UNSUPPORTED_TYPE: "SKILL_UNSUPPORTED_TYPE",
  SKILL_INVALID_SIDEEFFECT: "SKILL_INVALID_SIDEEFFECT",
  SKILL_INVALID_RISK_LEVEL: "SKILL_INVALID_RISK_LEVEL",
  SKILL_MARKDOWN_MISSING: "SKILL_MARKDOWN_MISSING",
  SKILL_DUPLICATE_NAME: "SKILL_DUPLICATE_NAME"
} as const;

export type SkillErrorCode = (typeof SKILL_ERROR_CODES)[keyof typeof SKILL_ERROR_CODES];
