export const DEMO_ORCHESTRATOR_ENGINE_ERROR_CODES = {
  INPUT_INVALID: "DEMO_ORCHESTRATOR_ENGINE_INPUT_INVALID",
  BUNDLE_INVALID: "DEMO_ORCHESTRATOR_ENGINE_BUNDLE_INVALID",
  ADAPTER_INCOMPATIBLE: "DEMO_ORCHESTRATOR_ENGINE_ADAPTER_INCOMPATIBLE",
  SLOT_ARTIFACT_MISSING: "DEMO_ORCHESTRATOR_ENGINE_SLOT_ARTIFACT_MISSING",
  PROJECTION_FAILED: "DEMO_ORCHESTRATOR_ENGINE_PROJECTION_FAILED",
  PROJECTION_AMBIGUOUS: "DEMO_ORCHESTRATOR_ENGINE_PROJECTION_AMBIGUOUS",
  CONDITION_UNKNOWN: "DEMO_ORCHESTRATOR_ENGINE_CONDITION_UNKNOWN",
  ROUTE_NOT_FOUND: "DEMO_ORCHESTRATOR_ENGINE_ROUTE_NOT_FOUND",
  ROUTE_AMBIGUOUS: "DEMO_ORCHESTRATOR_ENGINE_ROUTE_AMBIGUOUS",
  BINDING_SOURCE_MISSING: "DEMO_ORCHESTRATOR_ENGINE_BINDING_SOURCE_MISSING",
  BINDING_TARGET_INVALID: "DEMO_ORCHESTRATOR_ENGINE_BINDING_TARGET_INVALID",
  OVERLAY_UNKNOWN: "DEMO_ORCHESTRATOR_ENGINE_OVERLAY_UNKNOWN",
  OVERLAY_DENIED: "DEMO_ORCHESTRATOR_ENGINE_OVERLAY_DENIED",
  CALL_DEPTH_EXCEEDED: "DEMO_ORCHESTRATOR_ENGINE_CALL_DEPTH_EXCEEDED",
  RESUME_WITHOUT_CALLER: "DEMO_ORCHESTRATOR_ENGINE_RESUME_WITHOUT_CALLER",
  SUPPORTING_CALL_FORBIDDEN: "DEMO_ORCHESTRATOR_ENGINE_SUPPORTING_CALL_FORBIDDEN",
  BUDGET_EXHAUSTED: "DEMO_ORCHESTRATOR_ENGINE_BUDGET_EXHAUSTED",
  IDEMPOTENCY_CONFLICT: "DEMO_ORCHESTRATOR_ENGINE_IDEMPOTENCY_CONFLICT",
  SLOT_FAILED: "DEMO_ORCHESTRATOR_ENGINE_SLOT_FAILED",
  OUTPUT_INVALID: "DEMO_ORCHESTRATOR_ENGINE_OUTPUT_INVALID",
  AUDIT_FAILED: "DEMO_ORCHESTRATOR_ENGINE_AUDIT_FAILED"
} as const;

export type DemoOrchestratorEngineErrorCode =
  (typeof DEMO_ORCHESTRATOR_ENGINE_ERROR_CODES)[keyof typeof DEMO_ORCHESTRATOR_ENGINE_ERROR_CODES];

export class DemoOrchestratorEngineError extends Error {
  readonly code: DemoOrchestratorEngineErrorCode;

  constructor(code: DemoOrchestratorEngineErrorCode, message: string) {
    super(message);
    this.name = "DemoOrchestratorEngineError";
    this.code = code;
  }
}
