export type ScenarioOrchestratorCompileIssueCode =
  | "ORCHESTRATOR_COMPILE_INPUT_INVALID"
  | "ORCHESTRATOR_COMPOSITION_NOT_READY"
  | "ORCHESTRATOR_COMPOSITION_RESULT_MISMATCH"
  | "ORCHESTRATOR_COMPILE_PROFILE_NOT_FOUND"
  | "ORCHESTRATOR_COMPILE_PROFILE_INVALID"
  | "ORCHESTRATOR_PROFILE_COMPOSITION_MISMATCH"
  | "ORCHESTRATOR_PROFILE_SLOT_MISMATCH"
  | "ORCHESTRATOR_PROFILE_ROUTE_MISSING"
  | "ORCHESTRATOR_PROFILE_ROUTE_EXTRA"
  | "ORCHESTRATOR_ROUTE_PRIORITY_CONFLICT"
  | "ORCHESTRATOR_SLOT_ARTIFACT_MISSING"
  | "ORCHESTRATOR_SLOT_ARTIFACT_HASH_MISMATCH"
  | "ORCHESTRATOR_DOCUMENT_INVALID"
  | "ORCHESTRATOR_HASH_FAILED"
  | "ORCHESTRATOR_PARTIAL_RESULT_NOT_ALLOWED"
  | "ORCHESTRATOR_OUTPUT_PATH_UNSAFE"
  | "ORCHESTRATOR_RUNTIME_EXECUTION_FORBIDDEN"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_MISSING"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_INVALID"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_INCOMPLETE"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_EXTRA"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_PRIORITY_CONFLICT"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_PATH_UNSAFE"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_AMBIGUOUS"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_NO_MATCH"
  | "ORCHESTRATOR_OUTCOME_PROJECTION_MARKER_UNKNOWN";

export type ScenarioOrchestratorCompileIssue = {
  code: ScenarioOrchestratorCompileIssueCode;
  severity: "error" | "warning";
  message: string;
  compositionId?: string;
  routeId?: string;
  slotId?: string;
};
