export type ScenarioCompositionIssueCode =
  | "COMPOSITION_SCHEMA_INVALID"
  | "COMPOSITION_PATTERN_NOT_FOUND"
  | "COMPOSITION_PATTERN_VERSION_MISMATCH"
  | "COMPOSITION_EXECUTION_MODEL_UNSUPPORTED"
  | "COMPOSITION_PRIMARY_SLOT_MISSING"
  | "COMPOSITION_MULTIPLE_PRIMARY_SLOTS"
  | "COMPOSITION_SLOT_DUPLICATE"
  | "COMPOSITION_SLOT_ARCHETYPE_MISMATCH"
  | "COMPOSITION_PACK_CONFIG_INVALID"
  | "COMPOSITION_PACK_CONFIG_ARCHETYPE_MISMATCH"
  | "COMPOSITION_PATTERN_ARCHETYPE_MISMATCH"
  | "COMPOSITION_OVERLAY_LAYER_MISMATCH"
  | "COMPOSITION_SCOPE_TARGET_NOT_FOUND"
  | "COMPOSITION_ROUTE_SOURCE_NOT_FOUND"
  | "COMPOSITION_ROUTE_TARGET_NOT_FOUND"
  | "COMPOSITION_ROUTE_SELF_REFERENCE"
  | "COMPOSITION_BINDING_SOURCE_NOT_FOUND"
  | "COMPOSITION_BINDING_TARGET_NOT_FOUND"
  | "COMPOSITION_BINDING_TRANSFORM_UNSUPPORTED"
  | "COMPOSITION_PRECEDENCE_INCOMPLETE"
  | "COMPOSITION_CONFLICT_MODE_INVALID"
  | "COMPOSITION_PUBLIC_BOUNDARY_INVALID"
  | "COMPOSITION_DEEP_MERGE_NOT_ALLOWED";

export type ScenarioCompositionIssue = {
  code: ScenarioCompositionIssueCode;
  message: string;
  path?: string[];
};

export type ScenarioCompositionValidationResult = {
  ok: boolean;
  issues: ScenarioCompositionIssue[];
};
